In [1]:
# imports 

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from sklearn import datasets
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

In [2]:
df_diamonds = pd.read_csv("../data/diamonds_train.csv")
df_diamonds

,price,carat,city,depth,table,x,y,z,cut,color,clarity
0,4268,1.21,Dubai,62.4,58.0,6.83,6.79,4.25,Premium,J,VS2
1,505,0.32,Kimberly,63.0,57.0,4.35,4.38,2.75,Very Good,H,VS2
2,2686,0.71,Las Vegas,65.5,55.0,5.62,5.53,3.65,Fair,G,VS1
3,738,0.41,Kimberly,63.8,56.0,4.68,4.72,3.00,Good,D,SI1
4,4882,1.02,Dubai,60.5,59.0,6.55,6.51,3.95,Ideal,G,SI1
...,...,...,...,...,...,...,...,...,...,...,...
40450,10070,1.34,Antwerp,62.7,57.0,7.10,7.04,4.43,Ideal,G,VS1
40451,12615,2.02,Madrid,57.1,60.0,8.31,8.25,4.73,Good,F,SI2
40452,5457,1.01,Kimberly,62.7,56.0,6.37,6.42,4.01,Ideal,H,SI1
40453,456,0.33,Kimberly,61.9,54.3,4.45,4.47,2.76,Ideal,J,VS1
40454,6232,1.24,London,62.0,58.0,6.83,6.88,4.25,Ideal,I,SI1

In [3]:
df_diamonds_total =df_diamonds.drop(columns=["x","y","z"])

In [4]:
diamons_encoded= pd.get_dummies(df_diamonds_total, columns=["city","cut","color","clarity"], dtype=int)
diamons_encoded

,price,carat,depth,table,city_Amsterdam,city_Antwerp,city_Dubai,city_Kimberly,city_Las Vegas,city_London,...,color_I,color_J,clarity_I1,clarity_IF,clarity_SI1,clarity_SI2,clarity_VS1,clarity_VS2,clarity_VVS1,clarity_VVS2
0,4268,1.21,62.4,58.0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,1,0,0
1,505,0.32,63.0,57.0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,1,0,0
2,2686,0.71,65.5,55.0,0,0,0,0,1,0,...,0,0,0,0,0,0,1,0,0,0
3,738,0.41,63.8,56.0,0,0,0,1,0,0,...,0,0,0,0,1,0,0,0,0,0
4,4882,1.02,60.5,59.0,0,0,1,0,0,0,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40450,10070,1.34,62.7,57.0,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
40451,12615,2.02,57.1,60.0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
40452,5457,1.01,62.7,56.0,0,0,0,1,0,0,...,0,0,0,0,1,0,0,0,0,0
40453,456,0.33,61.9,54.3,0,0,0,1,0,0,...,0,1,0,0,0,0,1,0,0,0
40454,6232,1.24,62.0,58.0,0,0,0,0,0,1,...,1,0,0,0,1,0,0,0,0,0

In [9]:
# Create train and test (validation) samples
X= diamons_encoded.drop('price', axis=1)
y = diamons_encoded['price']

In [10]:
# Dividir los datos en conjuntos de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [11]:
# Crear un modelo de Random Forest Regressor
regressor = RandomForestRegressor(n_estimators=5000, random_state=42)

In [12]:
# Entrenar el modelo
regressor.fit(X_train, y_train)

RandomForestRegressor(n_estimators=5000, random_state=42)

In [13]:
predic = regressor.predict(X_test)

In [27]:
mse = mean_squared_error(y_test, predic)
print("RandomForestRegressor",mse)

RandomForestRegressor 310533.6644939415

In [28]:
r2_lmse = r2_score(y_test, predic)
r2_lmse

0.9809310678682585

In [15]:
from sklearn.metrics import root_mean_squared_error
mse= root_mean_squared_error(y_test, predic)
print(f"Root Mean Squared Error: {mse}")

Root Mean Squared Error: 557.2554750686094

In [23]:
df_diamonds_test= pd.read_csv("../data/diamonds_test.csv")
df_diamonds_test

,id,carat,cut,color,clarity,depth,table,x,y,z,city
0,0,0.79,Very Good,F,SI1,62.7,60.0,5.82,5.89,3.67,Amsterdam
1,1,1.20,Ideal,J,VS1,61.0,57.0,6.81,6.89,4.18,Surat
2,2,1.57,Premium,H,SI1,62.2,61.0,7.38,7.32,4.57,Kimberly
3,3,0.90,Very Good,F,SI1,63.8,54.0,6.09,6.13,3.90,Kimberly
4,4,0.50,Very Good,F,VS1,62.9,58.0,5.05,5.09,3.19,Amsterdam
...,...,...,...,...,...,...,...,...,...,...,...
13480,13480,0.57,Ideal,E,SI1,61.9,56.0,5.35,5.32,3.30,Amsterdam
13481,13481,0.71,Ideal,I,VS2,62.2,55.0,5.71,5.73,3.56,New York City
13482,13482,0.70,Ideal,F,VS1,61.6,55.0,5.75,5.71,3.53,Tel Aviv
13483,13483,0.70,Very Good,F,SI2,58.8,57.0,5.85,5.89,3.45,Surat
13484,13484,0.40,Ideal,I,VVS2,62.4,55.0,4.70,4.73,2.94,New York City

In [24]:
diamons_df_test1= pd.get_dummies(df_diamonds_test, columns=["city","cut","color","clarity"], dtype=int)
diamons_df_test1

,id,carat,depth,table,x,y,z,city_Amsterdam,city_Antwerp,city_Dubai,...,color_I,color_J,clarity_I1,clarity_IF,clarity_SI1,clarity_SI2,clarity_VS1,clarity_VS2,clarity_VVS1,clarity_VVS2
0,0,0.79,62.7,60.0,5.82,5.89,3.67,1,0,0,...,0,0,0,0,1,0,0,0,0,0
1,1,1.20,61.0,57.0,6.81,6.89,4.18,0,0,0,...,0,1,0,0,0,0,1,0,0,0
2,2,1.57,62.2,61.0,7.38,7.32,4.57,0,0,0,...,0,0,0,0,1,0,0,0,0,0
3,3,0.90,63.8,54.0,6.09,6.13,3.90,0,0,0,...,0,0,0,0,1,0,0,0,0,0
4,4,0.50,62.9,58.0,5.05,5.09,3.19,1,0,0,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13480,13480,0.57,61.9,56.0,5.35,5.32,3.30,1,0,0,...,0,0,0,0,1,0,0,0,0,0
13481,13481,0.71,62.2,55.0,5.71,5.73,3.56,0,0,0,...,1,0,0,0,0,0,0,1,0,0
13482,13482,0.70,61.6,55.0,5.75,5.71,3.53,0,0,0,...,0,0,0,0,0,0,1,0,0,0
13483,13483,0.70,58.8,57.0,5.85,5.89,3.45,0,0,0,...,0,0,0,0,0,1,0,0,0,0
13484,13484,0.40,62.4,55.0,4.70,4.73,2.94,0,0,0,...,1,0,0,0,0,0,0,0,0,1

In [25]:
x_test2 =diamons_df_test1.drop(columns=["x","y","z","id"])
x_test2

,carat,depth,table,city_Amsterdam,city_Antwerp,city_Dubai,city_Kimberly,city_Las Vegas,city_London,city_Luxembourg,...,color_I,color_J,clarity_I1,clarity_IF,clarity_SI1,clarity_SI2,clarity_VS1,clarity_VS2,clarity_VVS1,clarity_VVS2
0,0.79,62.7,60.0,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
1,1.20,61.0,57.0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,1,0,0,0
2,1.57,62.2,61.0,0,0,0,1,0,0,0,...,0,0,0,0,1,0,0,0,0,0
3,0.90,63.8,54.0,0,0,0,1,0,0,0,...,0,0,0,0,1,0,0,0,0,0
4,0.50,62.9,58.0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13480,0.57,61.9,56.0,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
13481,0.71,62.2,55.0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,1,0,0
13482,0.70,61.6,55.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
13483,0.70,58.8,57.0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
13484,0.40,62.4,55.0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,1

In [26]:
y_predic_test = regressor.predict(x_test2)
y_predic_test

array([ 2941.501  ,  5345.192  , 10736.585  , ...,  3171.984  ,
        2118.2126 ,   927.00568])

In [20]:
column_names = ["price"]
check_df = pd.DataFrame(y_predic_test, columns=column_names, index=diamons_df_test1['id'])
check_df.reset_index(inplace=True)
check_df

          id         price
0          0   2941.501000
1          1   5345.192000
2          2  10736.585000
3          3   4014.139000
4          4   1554.103822
...      ...           ...
13480  13480   1618.981600
13481  13481   2401.606600
13482  13482   3171.984000
13483  13483   2118.212600
13484  13484    927.005680

[13485 rows x 2 columns]

In [22]:
check_df.to_csv('archivotermin.csv', index=False)