In [41]:
# imports 

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from sklearn import datasets
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

In [42]:
df_diamonds = pd.read_csv("../data/diamonds_train.csv")
df_diamonds

,price,carat,city,depth,table,x,y,z,cut,color,clarity
0,4268,1.21,Dubai,62.4,58.0,6.83,6.79,4.25,Premium,J,VS2
1,505,0.32,Kimberly,63.0,57.0,4.35,4.38,2.75,Very Good,H,VS2
2,2686,0.71,Las Vegas,65.5,55.0,5.62,5.53,3.65,Fair,G,VS1
3,738,0.41,Kimberly,63.8,56.0,4.68,4.72,3.00,Good,D,SI1
4,4882,1.02,Dubai,60.5,59.0,6.55,6.51,3.95,Ideal,G,SI1
...,...,...,...,...,...,...,...,...,...,...,...
40450,10070,1.34,Antwerp,62.7,57.0,7.10,7.04,4.43,Ideal,G,VS1
40451,12615,2.02,Madrid,57.1,60.0,8.31,8.25,4.73,Good,F,SI2
40452,5457,1.01,Kimberly,62.7,56.0,6.37,6.42,4.01,Ideal,H,SI1
40453,456,0.33,Kimberly,61.9,54.3,4.45,4.47,2.76,Ideal,J,VS1
40454,6232,1.24,London,62.0,58.0,6.83,6.88,4.25,Ideal,I,SI1

In [66]:
# Calcular el volumen y agregar una nueva columna
df_diamonds['Volumen'] = df_diamonds['x'] * df_diamonds['y'] * df_diamonds['z']
df_diamonds

,price,carat,city,depth,table,x,y,z,cut,color,clarity,Volumen
0,4268,1.21,Dubai,62.4,58.0,6.83,6.79,4.25,Premium,J,VS2,197.096725
1,505,0.32,Kimberly,63.0,57.0,4.35,4.38,2.75,Very Good,H,VS2,52.395750
2,2686,0.71,Las Vegas,65.5,55.0,5.62,5.53,3.65,Fair,G,VS1,113.436890
3,738,0.41,Kimberly,63.8,56.0,4.68,4.72,3.00,Good,D,SI1,66.268800
4,4882,1.02,Dubai,60.5,59.0,6.55,6.51,3.95,Ideal,G,SI1,168.429975
...,...,...,...,...,...,...,...,...,...,...,...,...
40450,10070,1.34,Antwerp,62.7,57.0,7.10,7.04,4.43,Ideal,G,VS1,221.429120
40451,12615,2.02,Madrid,57.1,60.0,8.31,8.25,4.73,Good,F,SI2,324.276975
40452,5457,1.01,Kimberly,62.7,56.0,6.37,6.42,4.01,Ideal,H,SI1,163.990554
40453,456,0.33,Kimberly,61.9,54.3,4.45,4.47,2.76,Ideal,J,VS1,54.900540
40454,6232,1.24,London,62.0,58.0,6.83,6.88,4.25,Ideal,I,SI1,199.709200

In [ ]:
# Calcular el volumen como el producto de las columnas 'x' y 'z'
#df['volumen'] = df['x'] * df['z']

In [67]:
df_diamonds_total =df_diamonds.drop(columns=["x","y","z"])

In [68]:
diamons_encoded= pd.get_dummies(df_diamonds_total, columns=["city","cut","color","clarity"], dtype=int)
diamons_encoded

,price,carat,depth,table,Volumen,city_Amsterdam,city_Antwerp,city_Dubai,city_Kimberly,city_Las Vegas,...,color_I,color_J,clarity_I1,clarity_IF,clarity_SI1,clarity_SI2,clarity_VS1,clarity_VS2,clarity_VVS1,clarity_VVS2
0,4268,1.21,62.4,58.0,197.096725,0,0,1,0,0,...,0,1,0,0,0,0,0,1,0,0
1,505,0.32,63.0,57.0,52.395750,0,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
2,2686,0.71,65.5,55.0,113.436890,0,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
3,738,0.41,63.8,56.0,66.268800,0,0,0,1,0,...,0,0,0,0,1,0,0,0,0,0
4,4882,1.02,60.5,59.0,168.429975,0,0,1,0,0,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40450,10070,1.34,62.7,57.0,221.429120,0,1,0,0,0,...,0,0,0,0,0,0,1,0,0,0
40451,12615,2.02,57.1,60.0,324.276975,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
40452,5457,1.01,62.7,56.0,163.990554,0,0,0,1,0,...,0,0,0,0,1,0,0,0,0,0
40453,456,0.33,61.9,54.3,54.900540,0,0,0,1,0,...,0,1,0,0,0,0,1,0,0,0
40454,6232,1.24,62.0,58.0,199.709200,0,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0

In [69]:
# Create train and test (validation) samples
X= diamons_encoded.drop('price', axis=1)
y = diamons_encoded['price']

In [70]:
# Dividir los datos en conjuntos de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [71]:
# Crear un modelo de Random Forest Regressor
regressor = RandomForestRegressor(n_estimators=1000, random_state=42)

In [72]:
# Entrenar el modelo
regressor.fit(X_train, y_train)

RandomForestRegressor(n_estimators=1000, random_state=42)

In [73]:
predic = regressor.predict(X_test)

In [74]:
mse = mean_squared_error(y_test, predic)
print("lineal mode",mse)

lineal mode 308458.48263164103

In [75]:
r2_lmse = r2_score(y_test, predic)
r2_lmse

0.9810584985033804

In [76]:
from sklearn.metrics import root_mean_squared_error
mse= root_mean_squared_error(y_test, predic)
print(f"Root Mean Squared Error: {mse}")

Root Mean Squared Error: 555.3903875938447

In [77]:
df_diamonds_test= pd.read_csv("../data/diamonds_test.csv")
df_diamonds_test

,id,carat,cut,color,clarity,depth,table,x,y,z,city
0,0,0.79,Very Good,F,SI1,62.7,60.0,5.82,5.89,3.67,Amsterdam
1,1,1.20,Ideal,J,VS1,61.0,57.0,6.81,6.89,4.18,Surat
2,2,1.57,Premium,H,SI1,62.2,61.0,7.38,7.32,4.57,Kimberly
3,3,0.90,Very Good,F,SI1,63.8,54.0,6.09,6.13,3.90,Kimberly
4,4,0.50,Very Good,F,VS1,62.9,58.0,5.05,5.09,3.19,Amsterdam
...,...,...,...,...,...,...,...,...,...,...,...
13480,13480,0.57,Ideal,E,SI1,61.9,56.0,5.35,5.32,3.30,Amsterdam
13481,13481,0.71,Ideal,I,VS2,62.2,55.0,5.71,5.73,3.56,New York City
13482,13482,0.70,Ideal,F,VS1,61.6,55.0,5.75,5.71,3.53,Tel Aviv
13483,13483,0.70,Very Good,F,SI2,58.8,57.0,5.85,5.89,3.45,Surat
13484,13484,0.40,Ideal,I,VVS2,62.4,55.0,4.70,4.73,2.94,New York City

In [78]:
df_diamonds_test['Volumen'] = df_diamonds_test['x'] * df_diamonds_test['y'] * df_diamonds_test['z']
df_diamonds_test

,id,carat,cut,color,clarity,depth,table,x,y,z,city,Volumen
0,0,0.79,Very Good,F,SI1,62.7,60.0,5.82,5.89,3.67,Amsterdam,125.806866
1,1,1.20,Ideal,J,VS1,61.0,57.0,6.81,6.89,4.18,Surat,196.129362
2,2,1.57,Premium,H,SI1,62.2,61.0,7.38,7.32,4.57,Kimberly,246.878712
3,3,0.90,Very Good,F,SI1,63.8,54.0,6.09,6.13,3.90,Kimberly,145.593630
4,4,0.50,Very Good,F,VS1,62.9,58.0,5.05,5.09,3.19,Amsterdam,81.997355
...,...,...,...,...,...,...,...,...,...,...,...,...
13480,13480,0.57,Ideal,E,SI1,61.9,56.0,5.35,5.32,3.30,Amsterdam,93.924600
13481,13481,0.71,Ideal,I,VS2,62.2,55.0,5.71,5.73,3.56,New York City,116.477148
13482,13482,0.70,Ideal,F,VS1,61.6,55.0,5.75,5.71,3.53,Tel Aviv,115.898725
13483,13483,0.70,Very Good,F,SI2,58.8,57.0,5.85,5.89,3.45,Surat,118.874925
13484,13484,0.40,Ideal,I,VVS2,62.4,55.0,4.70,4.73,2.94,New York City,65.359140

In [79]:
diamons_df_test1= pd.get_dummies(df_diamonds_test, columns=["city","cut","color","clarity"], dtype=int)
diamons_df_test1

,id,carat,depth,table,x,y,z,Volumen,city_Amsterdam,city_Antwerp,...,color_I,color_J,clarity_I1,clarity_IF,clarity_SI1,clarity_SI2,clarity_VS1,clarity_VS2,clarity_VVS1,clarity_VVS2
0,0,0.79,62.7,60.0,5.82,5.89,3.67,125.806866,1,0,...,0,0,0,0,1,0,0,0,0,0
1,1,1.20,61.0,57.0,6.81,6.89,4.18,196.129362,0,0,...,0,1,0,0,0,0,1,0,0,0
2,2,1.57,62.2,61.0,7.38,7.32,4.57,246.878712,0,0,...,0,0,0,0,1,0,0,0,0,0
3,3,0.90,63.8,54.0,6.09,6.13,3.90,145.593630,0,0,...,0,0,0,0,1,0,0,0,0,0
4,4,0.50,62.9,58.0,5.05,5.09,3.19,81.997355,1,0,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13480,13480,0.57,61.9,56.0,5.35,5.32,3.30,93.924600,1,0,...,0,0,0,0,1,0,0,0,0,0
13481,13481,0.71,62.2,55.0,5.71,5.73,3.56,116.477148,0,0,...,1,0,0,0,0,0,0,1,0,0
13482,13482,0.70,61.6,55.0,5.75,5.71,3.53,115.898725,0,0,...,0,0,0,0,0,0,1,0,0,0
13483,13483,0.70,58.8,57.0,5.85,5.89,3.45,118.874925,0,0,...,0,0,0,0,0,1,0,0,0,0
13484,13484,0.40,62.4,55.0,4.70,4.73,2.94,65.359140,0,0,...,1,0,0,0,0,0,0,0,0,1

In [80]:
x_test2 =diamons_df_test1.drop(columns=["x","y","z","id"])
x_test2

,carat,depth,table,Volumen,city_Amsterdam,city_Antwerp,city_Dubai,city_Kimberly,city_Las Vegas,city_London,...,color_I,color_J,clarity_I1,clarity_IF,clarity_SI1,clarity_SI2,clarity_VS1,clarity_VS2,clarity_VVS1,clarity_VVS2
0,0.79,62.7,60.0,125.806866,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
1,1.20,61.0,57.0,196.129362,0,0,0,0,0,0,...,0,1,0,0,0,0,1,0,0,0
2,1.57,62.2,61.0,246.878712,0,0,0,1,0,0,...,0,0,0,0,1,0,0,0,0,0
3,0.90,63.8,54.0,145.593630,0,0,0,1,0,0,...,0,0,0,0,1,0,0,0,0,0
4,0.50,62.9,58.0,81.997355,1,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13480,0.57,61.9,56.0,93.924600,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
13481,0.71,62.2,55.0,116.477148,0,0,0,0,0,0,...,1,0,0,0,0,0,0,1,0,0
13482,0.70,61.6,55.0,115.898725,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
13483,0.70,58.8,57.0,118.874925,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
13484,0.40,62.4,55.0,65.359140,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,1

In [81]:
y_predic_test = regressor.predict(x_test2)
y_predic_test

array([2864.961     , 5369.138     , 9719.674     , ..., 3107.074     ,
       2127.298     ,  866.20566667])

In [82]:
column_names = ["price"]
check_df = pd.DataFrame(y_predic_test, columns=column_names, index=diamons_df_test1['id'])
check_df.reset_index(inplace=True)
check_df

          id        price
0          0  2864.961000
1          1  5369.138000
2          2  9719.674000
3          3  3965.532000
4          4  1670.136917
...      ...          ...
13480  13480  1632.946000
13481  13481  2414.391000
13482  13482  3107.074000
13483  13483  2127.298000
13484  13484   866.205667

[13485 rows x 2 columns]

In [85]:
check_df.to_csv('archivo_volumnen_sin_ejes.csv', index=False)